[package]
name = "modelUN"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "modelun"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
warp = "0.3"
include_dir = "0.7.4"
rand = "0.8.5"
uuid = { version = "1.13.1", features = ["v4"] }
log = "0.4"
env_logger = "0.11"